
# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: GFM
highlighter: rouge
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: USB-C Ham Radio Roundup
theme: jekyll-theme-hacker
title: USB-C Ham Radio Roundup
description: Naughty or Nice? USB-C ham radio testing & reviews for charger compatiblity

# Author/Organization info to be displayed in the templates
author:
  name: KK7LXU
  url: http://github.com/Animosity

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/USB-C-Radio-Roundup'

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
#logourl: /assets/img/dc_logo.png
#logoalt: The D.C. flag

# Navigation
# List links that should appear in the site sidebar here


# Repo list
# List repos that you would like to appear on the homepage here
#repos:
#- name: guides-template
#  description: 
#  url: https://github.com/DCgov/guides-template

# Style Variables
#brand_color: "#DA253B"
